builtins.fromJSON ''
  {
    "isLightMode": false,
    "doNotDisturb": false,
    "perMonitorWallpaper": false,
    "monitorWallpapers": {},
    "perModeWallpaper": false,
    "wallpaperPathLight": "",
    "wallpaperPathDark": "",
    "monitorWallpapersLight": {},
    "monitorWallpapersDark": {},
    "wallpaperTransition": "fade",
    "includedTransitions": [
      "fade",
      "wipe",
      "disc",
      "stripes",
      "iris bloom",
      "pixelate",
      "portal"
    ],
    "wallpaperCyclingEnabled": false,
    "wallpaperCyclingMode": "interval",
    "wallpaperCyclingInterval": 300,
    "wallpaperCyclingTime": "06:00",
    "monitorCyclingSettings": {},
    "nightModeEnabled": false,
    "nightModeTemperature": 4500,
    "nightModeHighTemperature": 6500,
    "nightModeAutoEnabled": false,
    "nightModeAutoMode": "time",
    "nightModeStartHour": 18,
    "nightModeStartMinute": 0,
    "nightModeEndHour": 6,
    "nightModeEndMinute": 0,
    "latitude": 0,
    "longitude": 0,
    "nightModeUseIPLocation": false,
    "nightModeLocationProvider": "",
    "pinnedApps": [],
    "hiddenTrayIds": [
      "steam",
      "KDE Connect Indicator"
    ],
    "recentColors": [],
    "showThirdPartyPlugins": false,
    "launchPrefix": "",
    "lastBrightnessDevice": "",
    "brightnessExponentialDevices": {},
    "brightnessUserSetValues": {},
    "brightnessExponentValues": {},
    "selectedGpuIndex": 0,
    "nvidiaGpuTempEnabled": true,
    "nonNvidiaGpuTempEnabled": false,
    "enabledGpuPciIds": [],
    "wifiDeviceOverride": "",
    "weatherHourlyDetailed": false,
    "configVersion": 2
  }
''
