inputs:
  system:
    description: 'The system to setup'
    default: 'x86_64-linux'
  cachixAuthToken:
    description: 'The token to use to authenticate with cachix'
runs:
  using: "composite"
  steps:
    - name: Install qemu
      if: ${{ inputs.system == 'aarch64-linux' }}
      shell: bash
      run: |
        sudo apt-get install -y qemu-user-static
    - uses: cachix/install-nix-action@V28
      with:
        extra_nix_config: |
          system = ${{ inputs.system }}
    - uses: DeterminateSystems/magic-nix-cache-action@v8
      with:
        upstream-cache: https://lpchaim.cachix.org
    - uses: cachix/cachix-action@v15
      with:
        name: lpchaim
        authToken: ${{ inputs.cachixAuthToken }}
