name: Setup build environment
description: Installs nix, sets up caches

inputs:
  system:
    description: 'The system to setup'
    default: 'x86_64-linux'
  cachixAuthToken:
    description: 'The token to use to authenticate with cachix'
  makeSpace:
    description: 'Whether or not to try to reclaim some space'
    default: false
runs:
  using: "composite"
  steps:
    - uses: samueldr/more-space-action@v2025-01-24.pre
      if: ${{ inputs.makeSpace == 'true' }}
      with:
        enable-lvm-span: true
        lvm-span-mountpoint: /nix
    - uses: samueldr/lix-gha-installer-action@v2026-02-16
      with:
        extra_nix_config: |
          extra-experimental-features = flakes nix-command pipe-operator
          system = ${{ inputs.system }}
    - name: Override nix-daemon build directory
      if: ${{ inputs.makeSpace == 'true' }}
      shell: bash
      run: |
        (
        PS4=" $ "
        set -eux -o pipefail
        sudo mkdir -p /nix/tmp
        sudo chmod ug=rwx,o=rwxt /nix/tmp
        sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
        sudo tee /etc/systemd/system/nix-daemon.service.d/override.conf >/dev/null <<EOF
        [Service]
        Environment=TMPDIR=/nix/tmp
        EOF
        sudo systemctl daemon-reload
        sudo systemctl restart nix-daemon
        )
    - uses: cachix/cachix-action@v16
      with:
        name: lpchaim
        authToken: ${{ inputs.cachixAuthToken }}
