name: Setup build environment
description: Installs nix and optionally qemu, sets up caches

inputs:
  system:
    description: 'The system to setup'
    default: 'x86_64-linux'
  cachixAuthToken:
    description: 'The token to use to authenticate with cachix'
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@V28
      with:
        extra_nix_config: |
          system = ${{ inputs.system }}
    - uses: DeterminateSystems/magic-nix-cache-action@v8
      with:
        upstream-cache: https://lpchaim.cachix.org
    - uses: cachix/cachix-action@v15
      with:
        name: lpchaim
        authToken: ${{ inputs.cachixAuthToken }}
