name: Push Raspberry Pi 4 build to Cachix

on:
  push:
    branches:
    - main
    - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install qemu
        run: |
          sudo apt-get install -y qemu-user-static
      - uses: cachix/install-nix-action@V28
        with:
          extra_nix_config: |
            system = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          upstream-cache: https://lpchaim.cachix.org
      - uses: cachix/cachix-action@v15
        with:
          name: lpchaim
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: |
          nix build .#nixosConfigurations.raspberrypi.config.system.build.toplevel
