password: ENC[AES256_GCM,data:yDYTXXnvBsVz70mW3qrany+3Mp9bboGCu8huU+g9NrvA0byPHAySxnuO1DIVV8dFSHLjOci7OKDAjtLyWF9YofrD6pfhNHxyHg==,iv:BbRfwswhd8yn+/g0Hyl0GXoZFOt08a+Tv+SLxbaqzl8=,tag:ZdQSaqeIPGGCu1XqvFWOAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tq2gcmu4hd4sd89hl7szhd0z8vg6tx9hk3xsvuljm9gsj7n0l4nsl6ad4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y1A3UTVCQktBZUw0MldP
            MzNTQ1JHWnNIc3dYckU0ZFVyVDg1U2g3YnlnCm9lZnluRUpQQU16MU1ncXVLMFdu
            Q1MvUnF3amNXcjhLeThZdnp3YmZzS0kKLS0tIGEwTDI5UGc5eVBSZjZRckZxdjhY
            ZGI4KzUyVWN6aWIyeXJDN2tRVjlud3MKUHZqmcPeo6aWIcdScz9UAe6Ndd9nZBEG
            H8VgOPOj2oebi6ppmU8KWLSQ0lYOZBL/JfC9urG7ZALiIvE8+4lTmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ke3gya92cy465lp9yxwygckgtg8tcsh366vgh4ywu6edl7a7ca0sgjxrjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MURjb0hVK1d6dmNwWEtr
            NnNoaHVGblE2Qm5DZlVnZFd1c2xkcmJiWUZjCjBxSUR2bFlmaDlWV1JxNEYxQmNX
            YlVCeitCemVRbi9SSmRGS3JtUVdGSjgKLS0tIGNxUUt5TnFxOFdPNUE1V1RtZW5z
            M0l2L0RHc3lIQnVEQmxwYVZwSDRwWUkKcf11agDFIBBn2dZ4Qch6MlK2ghi4Mcrm
            MirT4nrZUYQuvU0rtOuohR9iDRNumbXq53wJRSpLckcBFamu9w4liw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T18:02:46Z"
    mac: ENC[AES256_GCM,data:y2q3DeKwBkYhEMobrsTcrcfGqsKWxef8j6p4UZgiZTiW9uauFT4gXosN36pWGcugyNB7pC+Fzud+luKKpPhMM7vROYv4xXQ1bQ4/jRYVQQzsmqbOvgi1ppqS++8trYRvB3aFwZs/XkkzaB0tfQ/XIfjAyCIDRC0JSMY63YOo18c=,iv:kvzYpNRumASfGipGUOv4ZGS4r4u2O6poAJ7ZJiFhY6w=,tag:wSX7FAAeMYy5ZFLPwJNRoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
