password: ENC[AES256_GCM,data:yDYTXXnvBsVz70mW3qrany+3Mp9bboGCu8huU+g9NrvA0byPHAySxnuO1DIVV8dFSHLjOci7OKDAjtLyWF9YofrD6pfhNHxyHg==,iv:BbRfwswhd8yn+/g0Hyl0GXoZFOt08a+Tv+SLxbaqzl8=,tag:ZdQSaqeIPGGCu1XqvFWOAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tq2gcmu4hd4sd89hl7szhd0z8vg6tx9hk3xsvuljm9gsj7n0l4nsl6ad4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6emVQSU1SOWJBRnBlTGxl
            RHB1Rk9qK0FTanRBSC9NTEFpOHFDd1NvZFI0CnpKcWhNdEZwVE9Ib0JUQjFHcnpR
            b3dYTm9rNy9RN2NUaGhPNGpaTktINVkKLS0tIGZobDU4NDMyMGFDN1FOcFVrS3Jz
            bHExOEFTYnRlMTJ6SnNmZGUvS1I3SWsKsWs0SFYTXV8yYZDtwl896sbH6QTA6v5I
            nECz0H/wy0E9NzuYqEychTtZML1V6a4IzmcJM5adAHOOowYTWCBwlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ke3gya92cy465lp9yxwygckgtg8tcsh366vgh4ywu6edl7a7ca0sgjxrjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmdSK0JySjJxZEZxWmgr
            TEJlcmxzMUdnWDlPbW1UbGp2ZC95N3FwWHhBCnNBb2ZlNFRSNmtVTXNJRzNrK1R1
            alU5UWdlcjdEanp6d0oyYm9kWU9yYzAKLS0tIFEzU2p2cG9EMWRNcHFiTldIY25W
            QWFvU2gzaUFBZ0V5WGxCZmlrSHJBZXMK87vra3tTk4jQ7EGoy7PCwklxA9KPnvVC
            bQ2y76emJKArjJnxugL0wy7tHX1CbT3E0oIxw9tU1B1ozHB6qB0mtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cfshc5yzepc92mga9pclg6rcj084esq9a8tfe38m9c6mgzy5p5sqgc68u6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NjBGSVN3dGM2Z29UL1Za
            djAydytzT3FOK1k2RHg4b2hHZUZadlpaUTFvCmtRcUF6byttU29NUGxqRUdDenJN
            ZkluR3p2RTR6Qk5nNFNBMVYvOWpZN0EKLS0tIGphaUVpclRyUnljMUlwaFVRT2hK
            S2RwWmFmWW1xMHZ4Q0NTMUoxRm4yTkkKvZxhYIgTfrKk9e5+9/rZPN7nH0O3x/j+
            +l+pH0nYe/35wCds/P9jElhmvM2AnGAYOsRBE6NT8S5hvkEPyOxbhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T18:02:46Z"
    mac: ENC[AES256_GCM,data:y2q3DeKwBkYhEMobrsTcrcfGqsKWxef8j6p4UZgiZTiW9uauFT4gXosN36pWGcugyNB7pC+Fzud+luKKpPhMM7vROYv4xXQ1bQ4/jRYVQQzsmqbOvgi1ppqS++8trYRvB3aFwZs/XkkzaB0tfQ/XIfjAyCIDRC0JSMY63YOo18c=,iv:kvzYpNRumASfGipGUOv4ZGS4r4u2O6poAJ7ZJiFhY6w=,tag:wSX7FAAeMYy5ZFLPwJNRoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
