hello: ENC[AES256_GCM,data:eZ75CbaR9k+cK46YzNkguYvEZshEOB06LbK719mzuQF9vgKGnB3wH67tSegm5w==,iv:kpSLGrmXtp/ujuaLmN8q/O31VbxgfobqVqqja2QJ2jc=,tag:48ajPs0fdMMjlYBbqPPfEA==,type:str]
example_key: ENC[AES256_GCM,data:OB6nfXu42tLyRoWY0w==,iv:mB7c0/w69jt3kYWlxs3zjF0Hz+D5+Qlu0rnCpqB0x9I=,tag:K3sj42nKIPvfy3CM7Ve/dg==,type:str]
#ENC[AES256_GCM,data:/2vch3xwTFonpzZG/J93xw==,iv:G+nUCRC1Iwps9dxs8BEvwVoGXUcBks45HJOUkuOMJJM=,tag:I5nI1MbLPc8tBRIMl0jPZg==,type:comment]
example_array:
    - ENC[AES256_GCM,data:7MiAMFV8Orh0xoKojdY=,iv:fFeIUeT79k+zvQ9UbzFMybhiqsBM0Oik94eupRxiDl8=,tag:ir49eZptM4kWAqEO/SdJ4g==,type:str]
    - ENC[AES256_GCM,data:Ehh6r+gInjsX7t1nV9Y=,iv:kiMvG9VJeb9keGTixNoUNHk+X4WSOBYe0u9L79JHCbw=,tag:najo6Ic967WXpGeb9iffNw==,type:str]
example_number: ENC[AES256_GCM,data:vq5berW7Tbgn2g==,iv:0Sn1YUnp4C2IbFS3bvH5TZ1XNSs9U9dv+q45C+LLPP4=,tag:VhDSjKa9ai5LHv9N6IpfBw==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:+ZOp1Q==,iv:Kil1+oMXh+mxmxdlnlMo5PANnIh9tmwi4j5gqeYG7I0=,tag:xgwyC/B3pGFvVWcxLvatjA==,type:bool]
    - ENC[AES256_GCM,data:Yaoju4g=,iv:6vNUqAfvu5d56mInc2ZnNDMr7I+ojHaHORutITnSpv0=,tag:1if+2mpyFsAsTxmQgB26sg==,type:bool]
test: ENC[AES256_GCM,data:UZtQGuqCBuSSyUfqIQ==,iv:PV7Asc563b5kNUlu/CK+cugL0B4vpBHwYdW58s90QOM=,tag:wZcpDv8dyzkNQfvxZPXcSQ==,type:str]
your-secret: ENC[AES256_GCM,data:p3jfGqrUtxmn+af5NjFY,iv:Gs8kY9HcQjnSCmDQIuznrYd0lHQjeSYbUBpXMMkgCkM=,tag:tFygQvOPFxlywCC6rA+kwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fa7ce7w6q0ppk5l2gvg6d02g9cmj26rpt00ct54d4latqsnwajs90a43h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1emZJRnB5Q3hDbERTOGpi
            dDF5WUNiSmRxRkk2NVNrTkVEVlJPUWZGQ2wwClRKRDAwdHpBY2FQUXJQOGRzaWoy
            Z280YnJRZ2FNZFhhbk1ta2c5SDBCaTgKLS0tIDU1UTI1ZUFNdzFaYXBnK3pwbWJR
            UEp4enV1cTgxMGpUdU1sQ3dzWVYxYmsKOsePIaILcAbuOxJPlOEZgIFYgV3sDkTR
            2K8mWw+Dk2lSDMdlZHsSz04MDdA1vqxrLHnI/H5obeJ6c2HB4FY8tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T02:12:37Z"
    mac: ENC[AES256_GCM,data:vtBrp0tYcfzL+O2fqV7VLSD1yRZqkW4f1magm2pFLID02qxTZzqtG+EtEChWr5fCQRYQYT7CiPkXmY9OaVbTHUYRr5l1RCyJbrMRumaByzr1rcl8UJ0T+NGlV6ppb5Z2tGyX/RhqHsCnti8wgYAwwVA6MCudbux308ILousQUVE=,iv:2tWHkWM8OWDi3eT8WIkKZdJ7tfgDR8MC9a3LFk54mbA=,tag:QwG7s4DboPJ9cEEeLgAXFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
